app:
  name: app # 应用名称
  env: dev # 应用环境 dev|test|prod

http_server:
  log:
    # 仅在本地开发调试时打开
    # access_filename: "/dev/stdout"
    # error_filename: "/dev/stderr"

log:
  # 仅在本地开发调试时打开
  # filename: "/dev/stdout"

resty:

biz:
  allow_origins: [
      # 本地/测试等环境通配 正式环境须去除
      "*",
      "https://test.*.com",
      # 生产环境需配置域名列表
      "https://prod.*.com",
    ]

code:
  0: "成功"
  10000: "未知错误"
  10001: "三方服务错误"
  10002: "数据库错误"
  10003: "Redis错误"
  10004: "中间件服务错误"
  10005: "请求被取消"

  20000: "用户未登录"
  20001: "登录过期，请重新登录"
  20002: "用户无权限"
  20003: "参数非法"
  20004: "数据解析异常"
  20005: "数据不存在"
  20006: "数据冲突"
  20007: "系统维护中"
  20008: "操作过于频繁/未获得锁"
