// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	Username  string `gorm:"column:username;not null;comment:用户名" json:"username"` // 用户名
	Password  string `gorm:"column:password;not null;comment:密码" json:"password"`  // 密码
	BaseModel `json:"-"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
